name: Buf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Buf
        uses: bufbuild/buf-setup-action@main
        with:
          github_token: ${{ github.token }}
      - name: Buf Generate
        run: make pb
      - name: Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "ci: automatically update generated proto"
          delete-branch: true
          title: "ci: automatically update generated proto"
          body: "pb"
