name: Buf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Generate
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        go:
          - 1.17
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Go Install
        run: go install -v github.com/envoyproxy/protoc-gen-validate@v0.6.3
      - name: Buf
        uses: bufbuild/buf-setup-action@main
        with:
          github_token: ${{ github.token }}
      - name: Buf Generate
        run: make pb
